### ISSUE TITLE
http / is lipsum but it should lead to sign up

### ISSUE THREAD

**Issue by kengu2** [vaasahacklab/asylum#2]
If browsing to / the user is greeted with lorem ipsum without any links further. There should be link to sign up or redirect to sign up.

**Comment by olmari** [comment]
Would it be better to redirect to https://lataamo.vaasa.hacklab.fi/members/apply or to https://vaasa.hacklab.fi/hacklab/membership/ ?

**Comment by olmari** [comment]
Now / is redirected to https://vaasa.hacklab.fi/hacklab/membership/
