### ISSUE TITLE
add monthly fee monthly amount to invoice information

### ISSUE THREAD

**Issue by kengu2** [vaasahacklab/asylum#3]
invoices are of different values but there is no information on for how long the paid fee is good for as there is no information on the monthly amount in invoice.

Now it says "monthly fee mm/yyyy"

Should be "monthly fee x eur mm/yyyy" or something likes.

**Comment by olmari** [comment]
Now monthly fee invoice description states something like: "MONTHLY FEE 03/2017 - 07/2017, 10€ PER MONTH", initial support introduced in https://github.com/vaasahacklab/asylum/commit/45b5c3b9814750bdae2e0544d5bd03dbadd22a97 and made it to work in https://github.com/vaasahacklab/asylum/commit/5dae6d508b377fa92b5948b59c0689cd322869b5
